<?php
@define('_noidungdangcapnhat', 'Nội dung đang cập nhật');
@define('_khongcoketqua', 'Không tìm thấy kết quả phù hợp');
@define('_inputphonenumber', 'Nhập đúng định dạng số điện thoại Việt Nam');
@define('_nhaptukhoa', 'Vui lòng nhập từ khóa để tìm kiếm!');
@define('_timkiemsp', 'Tìm kiếm sản phẩm');
@define('_timkiemsanpham', 'Tìm kiếm sản phẩm');
@define('_nhapmabaove', 'Nhập mã bảo vệ');
@define('_tuvannhanh', 'Tư vấn nhanh');
@define('_goingay', 'Gọi ngay');
@define('_ngonngu', 'Ngôn ngữ');
@define('_lienhebaogia', 'Liên hệ báo giá');
@define('_sanphamlienquan', 'Sản phẩm liên quan');
@define('_duan', 'Dự án');
@define('_vechungtoi', 'Về chúng tôi');
@define('_cuachungtoi', 'Của chúng tôi');
@define('_hotrokythuat', 'Hỗ trợ kỹ thuật');
@define('_masanpham', 'Mã sản phẩm');
@define('_mangxahoi', 'Mạng XH');
@define('_motasanpham', 'Mô tả sản phẩm');
@define('_thongsokythuat', 'Thông số kỹ thuật');
@define('_downloadtailieu', 'Download tài liệu');
@define('_sanphamtuongtu', 'Sản phẩm tương tự');
@define('_xemgiohang', 'Xem giỏ hàng');
@define('_luotngangxemgiohang', 'Lướt ngang để xem hết giỏ hàng');
@define('_lienketnhanh', 'Liên kết nhanh');
@define('_tongcong', 'Tổng cộng');
@define('_tongdonhang', 'Tổng đơn hàng');
@define('_chuabaogomvat', 'Chưa bao gồm hóa đơn VAT và phí vận chuyển');
@define('_tieptucmuahang', 'Tiếp tục mua hàng');
@define('_thongtingiaohang', 'Thông tin giao hàng');
@define('_phuongthucvanchuyen', 'Phương thức vận chuyển');
@define('_giaotannoi', 'Giao tận nơi');
@define('_phuongthucthanhtoan', 'Phương thức thanh toán');
@define('_trovegiohang', 'Trở về giỏ hàng');
@define('_hoantatdonhang', 'Hoàn tất đơn hàng');
@define('_giohangcuaban', 'Giỏ hàng của bạn');
@define('_giaiphap', 'Giải pháp');
@define('_xem', 'Xem');
@define('_themvaogio', 'Thêm vào giỏ');
@define('_chonsoluong', 'Chọn số lượng');
@define('_sanphamcungdanhmuc', 'Sản phẩm cùng danh mục');
@define('_sanphamcuachungtoi', "Sản phẩm của chúng tôi");
@define('_xemsanpham', 'Xem sản phẩm');
@define('_chungnhan', 'Chứng nhận');
@define('_lienhevoichungtoiqua', 'Liên hệ với chúng tôi qua');
@define('_thoigianlamviec', 'Thời gian làm việc');
@define('_hotrokhachhang', 'Hỗ trợ khách hàng');
@define('_lienketmxh', 'Liên kết MXH');
@define('_hotro', 'Hỗ trợ');
@define('_tintucnoibat', 'Tin tức nổi bật');
@define('_thongtinsanpham', 'Thông tin sản phẩm');
@define('_sanphamcothebanquantam', 'Sản phẩm có thể bạn quan tâm');
@define('_dangkytuvan', 'Đăng ký tư vấn');
@define('_lienhechungtoi', 'Liên hệ chúng tôi');
@define('_ketquatimkiem', 'Kết quả tìm kiếm cho');
@define('_thongtinnhanhang', 'Thông tin nhận hàng');
@define('_hinhthucthanhtoan', 'Hình thức thanh toán');
@define('_giagoc', 'Giá gốc');
@define('_giakhuyenmai', 'Giá khuyến mãi');
@define('_workper', 'Giấy phép lao động Việt Nam');
@define('_temporary', 'Tạm trú thường trú');
@define('_giolamviec', 'Giờ làm việc');
@define('_whatwedo', 'Chúng tôi làm gì?');
@define('_deswhat', 'Chúng tôi tư vấn và cung cấp dịch vụ visa cho người nước ngoài vào việt nam, người nước ngoài cư trú tại việt nam.');
@define('_xemalldv', 'Xem tất cả dịch vụ');
@define('_dichvuchungtoi', 'Dịch vụ của chúng tôi');
@define('_ykienkhachhang', 'Ý kiến khách hàng');
@define('_motadownload', 'Download những tài liệu mới nhất của chúng tôi');
@define('_xemthem', 'Xem thêm');
@define('_taive', 'Tải về');
@define('_tuvan', 'Tư vấn');
@define('_sptieubieu', 'Sản phẩm tiêu biểu');
@define('_ketnoi', 'Kết nối với chúng tôi');
@define('_tiengviet', 'Tiếng việt');
@define('_tienganh', 'Tiếng anh');
//------------ Menu -----------------
@define('_trangchu', 'Trang chủ');
@define('_gioithieu', 'Giới thiệu');
@define('_tintuc', 'Tin tức');
@define('_sanpham', 'Sản phẩm');
@define('_tintucsukien', 'Tin tức - Sự kiện');
@define('_tuyendung', 'Tuyển dụng');
@define('_lienhe', 'Liên hệ');
@define('_khachhang', 'Khách hàng');
@define('_dichvu', 'Dịch vụ');
@define('_thietbi', 'Thiết bị vệ sinh');
@define('_dichvucungloai', 'Dịch vụ cùng loại');
@define('_chitietdichvu', 'Chi tiết dịch vụ');
@define('_xuatxu', 'Hãng sản xuất');
@define('_menu', 'Menu');
@define('_hinhanh', 'Hình ảnh');
@define('_video', 'Video clip');
@define('_sukien', 'Sự kiện');
@define('_khuyenmai', 'Khuyến mãi');
//-------- --------//
@define('_chitiet', 'Chi tiết');
@define('_dangluc', 'Đăng lúc');
@define('_daxem', 'Đã xem');
@define('_chitietbaiviet', 'Chi tiết bài viết');
@define('_cacbaivietkhac', 'Các bài viết khác');
@define('_chitietsanpham', 'Chi tiết sản phẩm');
@define('_gia', 'Giá');
@define('_maso', 'Mã số');
@define('_luotxem', 'Lượt xem');
@define('_sanphamcungloai', 'Sản phẩm cùng loại');
@define('_danhmucsanpham', 'Danh mục sản phẩm');
@define('_hinhanhsanpham', 'Hình ảnh sản phẩm');
@define('_thongketruycap', 'Thống kê truy cập');
@define('_homnay', 'Truy cập ngày');
@define('_trongthang', 'Truy cập tháng');
@define('_tongtruycap', 'Tổng truy cập');
@define('_daonline', 'Đã online');
@define('_hotrotructuyen', 'Hỗ trợ trực tuyến');
@define('_hotrokinhdoanhvatuvan', 'Hỗ trợ kinh doanh và tư vấn');
@define('_thongtinlienhe', 'Thông tin liên hệ');
@define('_danhchoquangcao', 'Dành cho quảng cáo');
@define('_doitac', 'Đối tác');
@define('_sanphamtieubieu', 'Sản phảm tiêu biểu');
@define('_ghichuthem', 'Ghi chú thêm');
@define('_duandamoinhat', 'Dự án mới nhất');
@define('_duandathuchien', 'Dự án đã thực hiện');
@define('_dangonline', 'Đang online');
@define('_luotonline', 'Lượt online');
@define('_xemtatca', 'Xem tất cả');
@define('_lienketwebsite', 'Liên kết website');
@define('_bando', 'Bản đồ');
@define('_nhaptensp', 'Nhập từ khóa để tìm kiếm');
@define('_timkiem', 'Tìm kiếm');
@define('_cacbaikhac', 'Các tin tức khác');
//------------- Contact --------
@define('_gui', ' Gửi ');
@define('_nhaplai', ' Nhập lại ');
@define('_diachi', 'Địa chỉ');
@define('_sodienthoai', 'Điện thoại');
@define('_hovaten', 'Họ và tên');
@define('_chude', 'Chủ đề');
@define('_noidung', 'Nội dung');
@define('_ghichu', 'Quý khách có thể liên hệ với chúng tôi từ website này bằng cách điền đầy đủ những thông tin vào form liên hệ bên dưới. Chúng tôi sẽ liên hệ với Quý khách trong thời gian sớm nhất. Xin chân thành cảm ơn.');
//------------------------------------//
@define('_readmore', 'Read more');
@define('_stay', 'Stay in touch');
@define('_enteremail', 'Enter email');
@define('_xemtiep', 'Xem tiếp >>');
@define('_tieptuc', 'Tiếp tục');
@define('_thongtinkhachhang', 'Thông tin khách hàng');
@define('_chuacodonhang', 'Hiện tại bạn chưa có đơn đặt hàng nào');
@define('_lichsumuahang', 'Lịch sử mua hàng');
@define('_conhang', 'Còn hàng');
@define('_tinhtrang', 'Tình trạng');
@define('_matkhaumoi', 'Mật khẩu mới');
@define('_thongtintaikhoan', 'Thông tin tài khoản');
@define('_doimatkhau', 'Đổi mật khẩu');
@define('_doithongtin', 'Thông tin tài khoản');
@define('_thoat', 'Thoát');
@define('_laylaimatkhau', 'Lấy lại mật khẩu');
@define('_clearcart', 'Bỏ tất cả sản phẩm ra khỏi giỏ hàng! ');
@define('_delcart', 'Bỏ sản phẩm này ra khỏi giỏ hàng!');
@define('_thanhtoan', 'Thanh toán');
@define('_capnhat', 'Cập nhật');
@define('_xoatatca', 'Xóa tất cả');
@define('_muatiep', 'Mua tiếp');
@define('_tonggiaban', 'Tổng giá bán');
@define('_tonggia', 'Tổng giá');
@define('_soluong', 'Số lượng');
@define('_ten', 'Tên');
@define('_stt', 'STT');
@define('_emaildaduocsudung', 'Email bạn nhập đã có người sử dụng');
@define('_taikhoanitnhat4kytu', 'Tài khoản phải từ 4 ký tự trở lên');
@define('_taikhoandasudung', 'Tài khoản bạn nhập đã có người dùng');
@define('_dedoimatkhau', 'để đổi lại mật khẩu');
@define('_dagoipassvaomail', 'Chúng tôi đã gởi mật khẩu mới vào mail của bạn! Bạn cần vào mail');
@define('_doipassthanhcong', 'Đổi mật khẩu thành công!');
@define('_capnhatthanhcong', 'Cập nhật thông tin thành công!');
@define('_dangnhapthanhcong', 'Đăng nhập thành công!');
@define('_thuchienkichhoattaikhoan', 'để thực hiện việc kích hoạt tài khoản');
@define('_dangkythanhcong', 'Đăng ký thành công! Bạn cần vào mail');
@define('_dangxuatthanhcong', 'Đăng xuất thành công');
@define('_nhanvaolinkdehoantat', 'Mời bạn nhấn vào link này để hoàn tất');
@define('_bandayeucaulaylaimatkhautai', 'Bạn đã yêu cầu lấy lại mật khẩu tại');
@define('_yeucaulaylaimatkhautai', 'Yêu cầu lấy lại mật khẩu tại');
@define('_emailchuadangky', 'Email bạn nhập chưa được đăng ký');
@define('_loiemail', 'Email không đúng');
@define('_saimatkhaucu', 'Mật khẩu cũ không đúng');
@define('_chuanhappassmoi', 'Bạn chưa nhập mật khẩu mới');
@define('_chuanhappasscu', 'Bạn chưa nhập mật khẩu cũ');
@define('_dehoanthanh', 'để hoàn thành đăng ký xin mời bạn click vào link phía dưới để kích hoạt tài khoản');
@define('_dangkytaitai', 'Bạn đã đăng ký tài khoản tại');
@define('_xinchao', 'Xin chào');
@define('_saimabaove', 'Nhập sai mã bảo vệ');
@define('_chuanhapdiachi', 'Bạn chưa nhập địa chỉ');
@define('_chuanhapsodienthoai', 'Bạn chưa nhập số điện thoại');
@define('_golaimatkhausai', 'Mật khẩu gõ 2 lần không giống nhau');
@define('_matkhauitnhat6kytu', 'Mật khẩu ít nhất 6 ký tự');
@define('_chuanhaplaimatkhau', 'Bạn chưa nhập lại mật khẩu');
@define('_chuanhapmatkhau_itnhat6kytu', 'Bạn chưa nhập mật khẩu (>=6 ký tự)');
@define('_error_tendangnhap', 'Tên đăng nhập ít nhất 6 ký tự');
@define('_tendangnhapkhongtontai', 'Tên đăng nhập không tồn tại');
@define('_taikhoanchuakichhoat', 'Tài khoản của bạn chưa được kích hoạt');
@define('_quenmatkhau', 'Quên mật khẩu');
@define('_saitendangnhap', 'Tên đăng nhập hoặc mật khẩu không chính xác');
@define('_chuadienmabaove', 'Bạn chưa điền mã bảo vệ.');
@define('_error_email', 'Vui lòng nhập đúng địa chỉ email');
@define('_chuadienmatkhau', 'Bạn chưa điền mật khẩu.');
@define('_chuadientendangnhap', 'Bạn chưa điền tên đăng nhập.');
@define('_masp', 'Mã SP');
@define('_thongtinchitiet', 'Thông tin chi tiết');
@define('_sanphamnoibat', 'Sản phẩm nổi bật');
@define('_lienketweb', 'Liên kết website');
@define('_thoitrangxaominh', 'Thời trang Xảo Minh');
@define('_sanphammoi', 'Sản phẩm mới');
@define('_dathang', 'Đặt hàng');
@define('_chinhsach', 'Chính sách');
@define('_muangay', 'Mua ngay');
@define('_muathem', 'Mua thêm sản phẩm khác');
@define('_tienhanh', 'Tiến hành đặt hàng');
@define('_nocart', 'Không có sản phẩm nào trong giỏ hàng');
@define('_thongbao', 'Thông báo !');
@define('_bancoxoa', 'Bạn có chắc chắn là muốn xóa sản phẩm này !');
@define('_dongy', 'Đồng ý ');
@define('_khongdongy', 'Không đồng ý ');
@define('_daxoathanhcong', 'Bạn đã xóa sản phẩm thành công. ');
@define('_dahuyxoa', 'Đã hủy việc xóa sản phẩm. ');
@define('_giohang', 'Giỏ hàng ');
@define('_dongia', 'Đơn giá ');
@define('_thanhtien', 'Thành tiền ');
@define('_tongtien', 'Tổng tiền ');
@define('_thongtindonhang', 'Thông tin đơn hàng ');
@define('_thongtinthanhtoan', 'Thông tin thanh toán ');
@define('_diachinhanhang', 'Địa chỉ nhận hàng ');
@define('_ghichudonhang', 'Ghi chú đơn hàng ');
@define('_chonhinhthucthanhtoan', 'Chọn hình thức thanh toán ');
@define('_thanhtoankhinhanhang', 'Thanh toán khi nhận hàng ');
@define('_thanhtoanbaokim', 'Thanh toán qua bảo kim ');
@define('_thanhtoannganluong', 'Thanh toán qua ngân lượng ');
@define('_thanhtoan123', 'Thanh toán qua 123 pay ');
@define('_chonnganhang', 'Chọn ngân hàng thanh toán');
@define('_banco', 'Bạn có');
@define('_lichsu', 'Lịch sử');
@define('_huongdanbaoduong', 'Hướng dẫn bảo dưỡng');
@define('_chinhanh', 'Chi nhánh');
?>